### ISSUE TITLE
Customize new todo input

### ISSUE THREAD

**Issue by mhmdtshref** [fack2/to-do-list-app#22]
Should customize the new todo input, it looks like it comes from a different app. I suggest this simple CSS design for it:

```css
#newToDo{
    height: 27px;
    border-radius: 10px;
    border: 2px solid #f7dfd4;
}
```
